---
title: "36-315 Interactive Project, Fall 2019"
author: "Jenny Zhu"
date: "Due Thursday, April 25th, 2019 (11:59pm ET) on Canvas"
output: 
  html_document:
    toc:  true
    toc_float:  true
    code_folding:  hide
---

#  Interactive Project:  Air Quality

**Organization, Themes, and HTML Output**

```{r, warning = F, message = F}
library(tidyverse)

jwzhu_315_theme <-  theme_bw() + # White background, purple and blue theme
  theme(axis.text = element_text(size = 12, color = "violetred"),
        text = element_text(size = 14, face = "italic", color = "royalblue3"))
```


## Reading in the Data

```{r, warning = FALSE, message = FALSE}
ozone <- read_csv("daily_44201_2018.csv")
pm25 <- read_csv("daily_88101_2018.csv")
```

## Choropleth Maps of Ozone and PM2.5 Levels

```{r, warning = FALSE, message = FALSE}
library(maps)
library(mapproj)
library(plotly)

names(ozone)
ozone <- mutate(ozone,
                `State Code` = as.numeric(`State Code`))
pm25 <- mutate(pm25,
               `State Code` = as.numeric(`State Code`))

warm_months <- seq(3:8)
ozone$season <- ifelse(as.numeric(substr(ozone$`Date Local`,6,7)) %in% warm_months, "warm","cold")

pm25$season <- ifelse(as.numeric(substr(pm25$`Date Local`,6,7)) %in% warm_months, "warm","cold")

ozone_cols <- ozone %>% select(`State Code`, season, `Arithmetic Mean`) %>% filter(season %in% c("warm", "cold"))

pm25_cols <- pm25 %>% select(`State Code`, season, `Arithmetic Mean`) %>% filter(season %in% c("warm", "cold"))

states_ozone <- ozone_cols %>%
group_by(`State Code`, season) %>% 
summarize(avg_ozone = mean(`Arithmetic Mean`))

states_pm25 <- pm25_cols %>%
group_by(`State Code`, season) %>% 
summarize(avg_pm25 = mean(`Arithmetic Mean`))

state_borders <- map_data("state") 
state_borders <- mutate(state_borders,
                        'FIPS' = as.double(state.fips$fips[match(region, state.fips$polyname)]))

#  join to state_borders
state_borders <- state_borders %>% select(long, lat, FIPS)

state_borders <- states_ozone %>%
  left_join(state_borders, by = c('State Code'='FIPS'))

state_borders <- state_borders %>%
  left_join(states_pm25, by = c('State Code'='State Code'))

ggplot(state_borders) + 
      geom_polygon(aes(x = long, y = lat, group = `State Code`,
                       fill = avg_ozone), color = "black") + 
      scale_fill_gradient2(low = "#2396B9", mid = "lightgrey", 
                           high = "#C70039", midpoint = 0.03) +
      theme_void() +
      coord_map("polyconic") + 
      labs(
        title = "Average Ozone Level in 2018 by State",
        #subtitle = "Percent of Population in State",
        #caption = "Zillow rental data",
        fill = "Average Ozone"
      ) + 
      theme(legend.position = "bottom") +
      facet_wrap(. ~ season.x) +
      jwzhu_315_theme

ggplot(state_borders) + 
      geom_polygon(aes(x = long, y = lat, group = `State Code`,
                       fill = avg_pm25), color = "black") + 
      scale_fill_gradient2(low = "#2396B9", mid = "lightgrey", 
                           high = "#C70039", midpoint = 15) +
      theme_void() +
      coord_map("polyconic") + 
      labs(
        title = "Average Ozone Level in 2018 by State",
        #subtitle = "Percent of Population in State",
        #caption = "Zillow rental data",
        fill = "Average Ozone"
      ) + 
      theme(legend.position = "bottom") +
      facet_wrap(. ~ season.x) +
      jwzhu_315_theme
```


```
The graph shows the average rent in January 2017 per state. It appears that the
state of California had the highest average rent out of all states (shaded
with purple), followed by several states in the upper east coast (New Jersey, 
New York, etc..). Some other high rent states are Washington and Colorado.
It appears that most states in the MidWest are relatively lower in terms of 
average rent, especially Oklahoma and Arkansas.  
```

c.  (18 points) 
```{r, warning = FALSE, message = FALSE}
southwest <- c(48, 40, 35, 4)
west <- c(6, 8, 16, 30, 32, 41, 49, 53, 56) 
midwest <- c(16, 17, 18, 19, 20, 26, 27, 29, 31, 38, 39, 46, 55)
southeast <- c(1, 5, 12, 13, 21, 22, 28, 37, 45, 47, 51, 54)
northeast <- c(9, 10, 11, 23, 24, 25, 27, 33, 34, 36, 42, 44, 50)

states_avg_pm25 <- aggregate(states_pm25[,3], 
                             list(states_pm25$`State Code`), mean)
states_avg_ozone <- aggregate(states_ozone[,3], 
                              list(states_ozone$`State Code`), mean)

states_air <- states_avg_pm25 %>% left_join(states_avg_ozone,
                                            by=c('Group.1'='Group.1'))

states_air <- mutate(states_air,
                     FIPS = Group.1,
                     Group.1 = state.fips$abb[match(Group.1, state.fips$fips)],
                     region = Group.1)

states_air[states_air$FIPS %in% southwest, ]$region = "southwest"
states_air[states_air$FIPS %in% west, ]$region = "west"
states_air[states_air$FIPS %in% midwest, ]$region = "midwest"
states_air[states_air$FIPS %in% southeast, ]$region = "southeast"
states_air[states_air$FIPS %in% northeast, ]$region = "northeast"

states_air <- states_air %>% filter(!is.na(Group.1))
states_air <- states_air[1:nrow(states_air)-1,] %>% select('Group.1','avg_pm25','avg_ozone','region')
states_dst <- dist(states_air,) 
dst <- as.matrix(states_dst) 
dst_i <- 1/dst 

library(qgraph)
library(plotly)

qgraph(dst_i, layout='spring', groups=states_air$region, vsize=3, labels=states_air$Group.1)
```

```{r}
library(shiny)
runApp()
library(rsconnect)
deployApp()
```

***
***
***
***
***
***


